spring.application.name=hospitalbackend
spring.datasource.url=jdbc:mysql://localhost:3306/anushka

spring.datasource.username=root

spring.datasource.password=Akoshta@0625

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true 